const fs = require('fs');
const path = require('path');
const sharp = require('sharp');

const assetsDir = path.join(__dirname, '../src/gameplay/fruits/assets');
const outputPublicDir = path.join(__dirname, '../public/assets/fruits');
const outputTsFile = path.join(__dirname, '../src/gameplay/fruits/FruitPNGs.ts');

if (!fs.existsSync(outputPublicDir)) {
  fs.mkdirSync(outputPublicDir, { recursive: true });
}

async function run() {
  const files = fs.readdirSync(assetsDir).filter(f => f.endsWith('.ts'));
  console.log('Found SVG files:', files);

  const pngDataUris = {};

  for (const file of files) {
    const filePath = path.join(assetsDir, file);
    const content = fs.readFileSync(filePath, 'utf-8');

    // Extract exported SVG strings: export const NameSVG = `...`;
    const regex = /export\s+const\s+(\w+)\s*=\s*`([\s\S]*?)`;/g;
    let match;
    while ((match = regex.exec(content)) !== null) {
      const varName = match[1];
      const svgContent = match[2].trim();

      console.log(`Processing ${varName}...`);
      try {
        const pngBuffer = await sharp(Buffer.from(svgContent))
          .resize(128, 128)
          .png()
          .toBuffer();

        // Save to public dir
        const fileName = `${varName}.png`;
        fs.writeFileSync(path.join(outputPublicDir, fileName), pngBuffer);

        // Save base64 Data URI
        const base64Uri = `data:image/png;base64,${pngBuffer.toString('base64')}`;
        pngDataUris[varName] = base64Uri;

        console.log(`✓ Generated ${fileName} (${pngBuffer.length} bytes)`);
      } catch (err) {
        console.error(`Error processing ${varName}:`, err);
      }
    }
  }

  // Generate TypeScript file
  let tsContent = `// Auto-generated by scripts/generate_fruit_pngs.cjs\n// High-resolution bitmap PNG Data URIs for bulletproof WebGL/Android WebView rendering\n\n`;
  tsContent += `export const FruitPNGDataURIs: Record<string, string> = {\n`;
  for (const [key, uri] of Object.entries(pngDataUris)) {
    tsContent += `  ${key}: '${uri}',\n`;
  }
  tsContent += `};\n`;

  fs.writeFileSync(outputTsFile, tsContent, 'utf-8');
  console.log(`✓ Written FruitPNGs.ts to ${outputTsFile}`);
}

run().catch(console.error);
